config/routes.rb
Eastonaiki::Application.routes.draw do
  
  root to: "static_pages#home"

  match '/wherenwhen',    to: 'map#index'
  match '/instructors',   to: 'static_pages#instructors'
  match '/aikidofaq',     to: 'faqs#index'
  match '/gallery',       to: 'gallery#index'
  match '/ourfriends',    to: 'static_pages#ourfriends'
  

  resources :faqs

end

app/models/faq.rb
# == Schema Information
#
# Table name: faqs
#
#  id         :integer         not null, primary key
#  question   :string(255)
#  answer     :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

class Faq < ActiveRecord::Base
  attr_accessible :answer, :question

  validates :question, presence: true, 
  					  length: { minimum: 10 }
  
  validates :answer, presence: true, 
  				    length: { minimum: 10 }				   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
	def index 
		@faqs = Faq.all 
	end	

	def show
  		@faq = Faq.find(params[:id])
	end	

	def new 
		@faq = Faq.new()			
	end	

	def create
		@faq = Faq.new(params[:faq])

		if @faq.save
        	redirect_to @faq, notice: 'User was successfully created.' 
		else
        	render action: "new" 
		end
    end

	def edit 
		@faq = Faq.find(params[:id])
	end 
	
	def update
		 @faq = Faq.find(params[:id])
		 if @faq.update_attributes(params[:faq])
		 	redirect_to @faq, notice: 'User was successfully updated.'
		 else	
			render action: "edit" 	
		 end	
	end 

	def distroy
		@faq = Faq.find(params[:id])
  		@faq.destroy

		redirect_to posts_url 
    end 	

end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
  def index
  end
end

app/controllers/map_controller.rb
class MapController < ApplicationController
  def index
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def wherenwhen
  end

  def instructors
  end

  def aikidofaq
  end

  def gallery
  end

  def ourfriends
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis.
	def full_title(page_title)
		base_title = "Easton Aikido"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/faqs/_form.html.haml
= form_for @faq do |f| 
  - if @faq.errors.any? 
    .errorExplanation
      %h2
        = pluralize(@faq.errors.count, "error")
        prohibited this faq from being saved:
      %ul
        - @faq.errors.full_messages.each do |msg| 
          %li 
            = msg 
  %p
    = f.label :question 
    %br  
    = f.text_field :question 
  %p
    = f.label :answer 
    %br
    = f.text_field :answer 
  %p
    = f.submit 

app/views/faqs/edit.html.haml
= render 'form'

= link_to 'show', :action => :show, :id => @faq.id   
= link_to 'Back', :action => :index   

app/views/faqs/index.html.haml
.page-header
	%h1 Aikido FAQ's <small>click on a question to see the answer</small>
%section
	%ul.questions
		- @faqs.each do |post|
			%li 
				= link_to post.question, "##{ post.id }" 
				.hide{ id:"#{ post.id }" } 
					= post.answer
			

app/views/faqs/new.html.haml
= render 'form'
   
= link_to 'Back', :action => :index   

app/views/faqs/show.html.haml
%p
	= @faq.question 
	%br  
	= @faq.answer 
   
= link_to 'Back', :action => :index   

app/views/gallery/index.html.haml
.page-header
	%h1 And now time for the gallery ...
%section
	.row
		.span4
			.project-gallery
				%a{ href:'//d6pz16ai3czu.cloudfront.net/f6bf104e-cb29-411d-901f-0f28b4c5d3fb_large_visualisation.jpg', class:'img-container gallery', rel:'project-gallery', title:'How it will look: Cody Dock opened up with new swing bridge' }
					.image 
						= image_tag('//d6pz16ai3czu.cloudfront.net/f6bf104e-cb29-411d-901f-0f28b4c5d3fb_medium_visualisation.jpg')

					.img-link View gallery

				%ul.img-thumbs
					%li
						%a{ href:'//d6pz16ai3czu.cloudfront.net/eec46948-f6e9-466d-9da8-22456aafe62d_large_final-logo.jpg', class:'gallery', title:'title one', rel:'project-gallery' }
							= image_tag('//d6pz16ai3czu.cloudfront.net/eec46948-f6e9-466d-9da8-22456aafe62d_small_final-logo.jpg')
					%li
						%a{ href:'//d6pz16ai3czu.cloudfront.net/e518cd59-3c04-4c3b-baeb-aea858d8a444_large_mouth-of-dock.jpg', class:'gallery', title:'title two', rel:'project-gallery' }
							= image_tag('//d6pz16ai3czu.cloudfront.net/e518cd59-3c04-4c3b-baeb-aea858d8a444_small_mouth-of-dock.jpg')
					%li
						%a{ href:'//d6pz16ai3czu.cloudfront.net/5a061219-b92c-4b57-97ca-a71f08110615_large_bridge-plans.jpg', class:'gallery', title:'title three', rel:'project-gallery' }
							= image_tag('https://d6pz16ai3czu.cloudfront.net/5a061219-b92c-4b57-97ca-a71f08110615_small_bridge-plans.jpg')				
		.span8
			%p
				this is a test gallery from spacehive about a curren project cody dock. 

app/views/layouts/_footer.html.haml
%footer.footer
	%nav
		:markdown 
			- For more information contact Sean @ [sf2603@gmail.com](mailto:sf2603@gmail.com)        

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top
	.navbar-inner
		.container
			= link_to "Aikido", '#', id: "logo"
			%nav
				%ul.nav.pull-right
					%li= link_to "Home", root_path 
					%li= link_to "Where n When", wherenwhen_path 
					%li= link_to "Instructors", instructors_path
					%li= link_to "Aikido FAQ", aikidofaq_path
					%li= link_to "Gallery", gallery_path
					%li= link_to "Our Friends", ourfriends_path

app/views/layouts/_shim.html.haml
/[if lt IE 9]
	%script src="http://html5shim.googlecode.com/svn/trunk/html5.js"    	

app/views/layouts/application.html.haml
!!!
%html
	%head
		%title= full_title(yield(:title))
		= stylesheet_link_tag "application", media: "all" 
		= javascript_include_tag "application"
		= yield(:head)
		= csrf_meta_tags
		= render 'layouts/shim'
	%body
		= render 'layouts/header'
		.container
			= yield
		= render 'layouts/footer'	

app/views/map/index.html.haml
= content_for(:head) do
	= javascript_include_tag "//maps.googleapis.com/maps/api/js?sensor=false&region=GB" 
	
.page-header
	%h1 Where n When

%section
	.row
		.span6
			%span{ id:"map_canvas", style:"display: block; width: 450px; height: 350px; margin-top:10px;" }
				%noscript
				= image_tag("//maps.googleapis.com/maps/api/staticmap?zoom=15&size=750x430&maptype=roadmap&markers=color:red%7Clabel:A%7C51.4592415, -2.5627648&sensor=false") 
		.span6
			%h3 How to get there 
			%p
				look at the map!
			%h3 Class times 
			%p
				Every friday 7:00 - 9:00
			%h3 What to expect
			%p
				the unexpected!

app/views/static_pages/faq.html.haml
:markdown	
				- [how long will it take to be a master](#a2)
			#a2.hide the road to enligntenment is never ending
			:markdown
				- [will this stop me being bullied](#a3) 
			#a3.hide No chance fatso
			:markdown
				- [when do i get a sword](#a4)
			#a4.hide when you mind is shaper than your ego 
			:markdown
				- [is this the ultimate fitghting technique](#a5)
			#a5.hide
				:markdown

					[wing chun kung fu]('http://www.ipman-movie.com/main_en.html')


					

   					   

app/views/static_pages/gallery.html.haml
.page-header
	%h1 gallery
%section
	.row
		.span4
			.project-gallery
				%a{ href:'//d6pz16ai3czu.cloudfront.net/f6bf104e-cb29-411d-901f-0f28b4c5d3fb_large_visualisation.jpg', class:'img-container gallery', rel:'project-gallery', title:'How it will look: Cody Dock opened up with new swing bridge' }
					.image 
						= image_tag('//d6pz16ai3czu.cloudfront.net/f6bf104e-cb29-411d-901f-0f28b4c5d3fb_medium_visualisation.jpg')

					.img-link View gallery

				%ul.img-thumbs
					%li
						%a{ href:'//d6pz16ai3czu.cloudfront.net/eec46948-f6e9-466d-9da8-22456aafe62d_large_final-logo.jpg', class:'gallery', title:'title one', rel:'project-gallery' }
							= image_tag('//d6pz16ai3czu.cloudfront.net/eec46948-f6e9-466d-9da8-22456aafe62d_small_final-logo.jpg')
					%li
						%a{ href:'//d6pz16ai3czu.cloudfront.net/e518cd59-3c04-4c3b-baeb-aea858d8a444_large_mouth-of-dock.jpg', class:'gallery', title:'title two', rel:'project-gallery' }
							= image_tag('//d6pz16ai3czu.cloudfront.net/e518cd59-3c04-4c3b-baeb-aea858d8a444_small_mouth-of-dock.jpg')
					%li
						%a{ href:'//d6pz16ai3czu.cloudfront.net/5a061219-b92c-4b57-97ca-a71f08110615_large_bridge-plans.jpg', class:'gallery', title:'title three', rel:'project-gallery' }
							= image_tag('https://d6pz16ai3czu.cloudfront.net/5a061219-b92c-4b57-97ca-a71f08110615_small_bridge-plans.jpg')				
		.span8
			%p
				this is a test gallery from spacehive about a curren project cody dock. 

app/views/static_pages/home.html.haml
.page-header
	%h1 Welcome to EastonAiki <small>the aikdo club for pumpers!</small>

%section
	= image_tag('flyer.jpg')

app/views/static_pages/instructors.html.haml
.page-header
	%h1 Destructors!
%section
	.row
		.span4
			= image_tag('sean.jpg')
		.span8 
			%p
				Sean started practicing aikido at the Wa Go Kan dojo under the guidance of Yates Sensei in 2004. Since then as well as practicing 4 times a week in Manchester, Sean attends many other dojos and aikido courses in the UK to further augment and broaden his understanding of aikido generally. This desire to gain a deeper understanding took Sean to Tokyo in 2007/08 for a year to train under the current Doshu and various other Shihan at the Hombu Dojo in Tokyo. Whilst there Sean achieved the level of Shodan. Whenever he can Sean also studies and trains under Yamashima Shihan (7th dan aikikai) who, as well as regularly attending morning practice under the current Doshu, runs both the Chioda-Ku and the Miname Tanaka dojos in Tokyo, Yamashima Shihan was a long time student of Yamaguchi Shihan (8th dan aikikai). As well as training as often as possible Sean furthers his learning of aikido by regularly facilitating practice on Saturday mornings at the Wa Go Kan dojo in Manchester.  In May 2010 Sean attained the rank of 2nd dan during a visit to Hombu dojo.	

app/views/static_pages/ourfriends.html.haml
.page-header
	%h1 Our friends
%section 
	%h3 Sub heading 
	:markdown
		- [link one](#) - short desc
		- [link two](#) - short desc
		- [link three](#) - short desc 
	%h3 Sub heading 
	:markdown
		- [link one](#) - short desc
		- [link two](#) - short desc
		- [link three](#) - short desc 	

app/views/static_pages/wherenwhen.html.haml
= content_for(:head) do
	= javascript_include_tag "//maps.googleapis.com/maps/api/js?sensor=false&region=GB" 
	= javascript_include_tag "map"

.page-header
	%h1 Where n When

%section
	.row
		.span6
			%span{ id:"map_canvas", style:"display: block; width: 450px; height: 350px; margin-top:10px;" }
				%noscript
				= image_tag("//maps.googleapis.com/maps/api/staticmap?zoom=15&size=750x430&maptype=roadmap&markers=color:red%7Clabel:A%7C51.44875,-0.322626&sensor=false") 
		.span6
			%h3 How to get there 
			%p
				look at the map!
			%h3 Class times 
			%p
				Every friday 7:00 - 9:00
			%h3 What to expect
			%p
				the unexpected!